<#
example.ps1
サンプル PowerShell スクリプト
用途: 実行サンプル、パラメータ、ログ出力、エラーハンドリングの例

使い方（Windows の PowerShell / pwsh から）:
  powershell.exe -NoProfile -ExecutionPolicy Bypass -File "D:\BATCH\PG\practice\powershell\example.ps1" -Name "Hiro" -Verbose
  pwsh -NoProfile -ExecutionPolicy Bypass -File "D:\BATCH\PG\practice\powershell\example.ps1" -- -Name "Hiro" -Verbose

WSL から (bash):
  winpath=$(wslpath -w /mnt/d/BATCH/PG/practice/powershell/example.ps1)
  /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$winpath" -Name "Hiro"

#>
[CmdletBinding()]
param(
    [Parameter(Position=0)]
    [string]$Name = 'World',

    [switch]$Verbose,

    [string]$LogFile = "$PSScriptRoot\example.log"
)

function Write-Log {
    param(
        [Parameter(Mandatory=$true)] [string]$Message,
        [ValidateSet('INFO','WARN','ERROR')] [string]$Level = 'INFO'
    )
    $timestamp = (Get-Date).ToString('yyyy-MM-dd HH:mm:ss')
    $line = "${timestamp} [$Level] $Message"
    # コンソール出力
    if ($PSBoundParameters.ContainsKey('Verbose') -or $VerbosePreference -ne 'SilentlyContinue') {
        Write-Host $line
    } else {
        Write-Output $line
    }
    # ログファイルへ追記（エラー時も続行）
    try {
        Add-Content -Path $LogFile -Value $line -Encoding UTF8
    } catch {
        Write-Warning "ログファイルに書き込みできません: $LogFile ($_ )"
    }
}

# スクリプト開始
try {
    Write-Log -Message "Script started. PSVersion: $($PSVersionTable.PSVersion)" -Level INFO

    Write-Log -Message "Script directory: $PSScriptRoot" -Level INFO
    Write-Log -Message "Name parameter: $Name" -Level INFO

    # サンプル処理: 簡単なファイル作成とディレクトリ一覧
    $outFile = Join-Path -Path $PSScriptRoot -ChildPath "greeting.txt"
    "Hello, $Name! This file was generated by example.ps1 on $(Get-Date)" | Out-File -FilePath $outFile -Encoding UTF8
    Write-Log -Message "Created file: $outFile" -Level INFO

    Write-Log -Message "Directory listing (first 20 items):" -Level INFO
    Get-ChildItem -Path $PSScriptRoot -Force -ErrorAction Stop | Select-Object -First 20 | ForEach-Object {
        Write-Log -Message " - $($_.Name)" -Level INFO
    }

    Write-Log -Message "Script completed successfully." -Level INFO
    exit 0
} catch {
    Write-Log -Message "Unhandled error: $_" -Level ERROR
    exit 1
}
