Vagrant.configure("2") do |config|
  config.vm.box = ""
  config.vm.hostname = ""
  config.vm.provider "" do |v|
    v.memory = 
    v.cpus = 
  end

  config.vm.network "", ip: ""
  config.vm.provider :virtualbox do |vb|
    vb.customize ['createhd', '--filename', 'disk1.vdi', '--size', 16384, '--variant', 'dynamic']
    vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', 'disk1.vdi']
  end
end
