Vagrant.configure("2") do |config|
  config.vm.box = "generic/rhel9"
  config.vm.hostname = "rhel9-vm"
  config.vm.network "private_network", ip: "192.168.100.20"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end
end
